### ISSUE TITLE
ctags: Notice: xcmd recognizes .../coffeetags is not available

### ISSUE THREAD

**Issue by marlun** [kopischke/homebrew-ctags#3]
After installing whenever I run ctags I'm getting the following notice:

    ctags: Notice: xcmd recognizes /usr/local/Cellar/ctags-fishman/HEAD/libexec/ctags/drivers/coffeetags is not available

I guess it's for CoffeeScript but as I don't care much about that could I just tell it to ignore that?

**Comment by kopischke** [comment]
This is the repo for the [Homebrew](http://brew.sh/) recipe for the fishman ctags fork, not for the fork itself – you will have to report this issue [on the ctags repo](https://github.com/fishman/ctags/issues).
